server:
  port: 8016
  servlet:
    context-path: /demo/api
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

mybatis:
  mapper-locations: classpath:mapping/*.xml
  check-config-location: true
  type-aliases-package: org.spring.boot.po

pagehelper:
  autoDialect: true
  closeConn: false
  reasonable: true

spring:
  devtools:
    restart:
      enabled: true
  profiles:
    active: dev